# .github/workflows/ci.yml
name: ChessAnalyzer CI

# This workflow runs on pushes to the 'main' branch and on any pull request.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define the matrix strategy to test against multiple Python versions
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    # Step 1: Check out the repository code
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up the specified Python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry' # Cache Poetry's virtualenv

    # Step 3: Install Poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1

    # Step 4: Install project dependencies using Poetry
    - name: Install dependencies
      run: poetry install --with dev

    # Step 5: Run the Linter with Ruff (checks for style issues and common errors)
    - name: Lint with Ruff
      run: poetry run ruff check .

    # Step 6: Run the Static Type Checker with MyPy
    - name: Check types with MyPy
      run: poetry run mypy chess_analyzer/

    # Step 7: Run the Unit Tests with Pytest
    - name: Test with Pytest
      run: poetry run pytest
